### ISSUE TITLE
Video playback incorrectly stopped when disconnecting a Bluetooth headset

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#162]
When disconnecting a Bluetooth headset with the app built for iOS 14, video playback is incorrectly stopped instead of simply paused.

### Issue type

Incorrect behavior

### Environment information

* Application version: 3.x.x built with iOS 14 SDK
* iOS version: 14
* Device: Physical

### Reproducibility

Always reproducible

### Steps to reproduce

1. Connect a Bluetooth headset.
1. Open a video clip and play for a bit.
1. Disconnect the headset (e.g. remove both Airpods from your ears).
1. Playback is stopped. Resuming restarts at the beginning.

**Comment by defagos** [comment]
This does not happen if the app was built with the iOS 13.7 SDK. Having a look at the code responsible for the stop:

- Why is there a stop and simply not a pause? (probably because it was mitigating the crash).
- The condition is not fine enough and probably triggered for more legitimate reasons when built / run for iOS 14.
- Removing the code entirely works as expected on iOS 14 without crashing.

I propose we remove the offending code and test the behavior on iOS 12 and 13. If no crash occurs we are done.

**Comment by defagos** [comment]
Fix available for test and review on `feature/bluetooth-stop-fix`.

**Comment by pyby** [comment]
Tested on iOS 12 and iOS 13 devices with Bluetooth headsets (AirPods Pro in my case).
I confirmed no regression and fix this issue.

The offending code was introduced with the video background playback feature. Maybe useful for iOS 9, 10, 11, or just something added but not required.
