### ISSUE TITLE
Popover anchoring issue on iOS 14

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#163]
The search settings popover anchor moves when interacting with a setting. This is only visible on iOS 14 but might be related to a bug which existed before but with less visible effects.

### Issue type

Incorrect behavior

### Environment information

* Application version: 3.1.4
* iOS version: 14
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Open search settings on an iPad in landscape orientation.
1. Tap on some setting.
1. The popover moves to the top left.

This is related to the underlying view being reloaded (commenting out the cell didSelect method fixes the issue). Maybe this is related to the bar button item anchor being recreated in the process.

**Comment by defagos** [comment]
Avoiding unnecessary button destruction and creation fixes the issue.

We still have an issue with the popover content disappearing and staying invisible after a rotation, but I could trace it back to the use of Fingertips. I will have a look if something can be done, otherwise this is not a severe issue as this code is not added in production builds.

**Comment by defagos** [comment]
Fixed on the {{feature/popover-fix}} branch. I also updated other popovers (working well) to anchor them to a bar button item.

I have no clue for Fingertips at the moment, but this is not a serious issue (we must only keep it in mind in internal builds).

**Comment by pyby** [comment]
Thank you for explaining here the "transparence popover after rotation" issue, because of `Fingertips` SDK. This SDK is not included in the production build, and I checked again that the issue is not reproducible in the AppStore build.

Thank you to found this bug issue, and the fix.
