### ISSUE TITLE
Remote configuration is not updated after a while

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#165]
Since a few weeks we observe a strange behavior with the remote configuration. It seems to be lost after several hours (24?), reverting back to the embedded configuration instead of the last fetched one. Killing and restarting the app fetches the remote configuration again, but this is a bit sad.

We updated Firebase SDK, was there a regression or did we miss something?

**Comment by defagos** [comment]
Tested today with latest betas on which we experienced this issue, opened after more than one day. Might be related to a temporary Firebase backend issue, now the problem seems gone.

**Comment by pyby** [comment]
Some test results are in https://jira.srg.beecollaboration.com/browse/PLAYRTS-2000.

**Comment by defagos** [comment]
Firebase SDK seems to work as expected, so the problem is likely on our side.

Fix proposal on the `feature/remote-config-fix` branch:

- Removal of the activate call at startup, which probably interleaves with the fetch-activate triggered right afterwards. According to some tests this was unnecessary.
- Use same settings for nightlies, betas and production versions (during 15 minutes after the last successful remote configuration retrieval the SDK inhibits other attempts). This way it is easier to test the production behavior with nightlies.

**Comment by pyby** [comment]
Your proposition to remove the activate call at startup is a revert commit to c0a84e5d0d77dbbb3eea526f155727c13e4c6ccf.
This old commit was introduced during the tvOS epic, at the migration of iOS project from Carthage to SPM.

Two commit later, ff81c440eae5923979a77aa2e5ea72dfabe1bd21, 4 hours and a half later, the `FirebaseRemoteConfigStorageFix.m` workaround was introduced for FireBase on tvOS.

We were not aware of the Firebase storage issue on tvOS. The first commit to call the activate method at startup was a first try to fix remote configuration on tvOS. It wasn't a success.
The second commit to move FireBase database to caches directory worked.

But we kept the first commit.

From your findings and tests, it sounds a good idea to remote it.

Let's test in a nighty build.

**Comment by pyby** [comment]
The "revert" commit works as expected on the nightlies:
- **After a remote configuration update on FireBase**: 15 minutes later in the background, application reopened displays the previous configuration, and fetches the new configuration in background. Kill and reopen the app displays the new configurations. Application configuration is updated and displays the new informations.
- **With a remote configuration not changed** (but different from the local configuration): 15 minutes later with the application killed, application launches and displays the cached remote configuration. No restauration to the local configuration. Application still has the correct configuration and displays the informations.

Tested on:
- iOS 14.2
- iPadOS 14.2
- tvOS 14.3 beta.

**Comment by pyby** [comment]
Just updated the application won't update missing update. In my test, "last chance" swimlane is missing.

- Updated the remote configuration key without changing the string does not update the local cached value. "last chance" swimlane is still missing.
- Updated the remote configuration key with an unknown section that changing the string does update the local cached value: "last chance" swimlane is displayed.

**Comment by pyby** [comment]
Fix proposal on the `feature/reset-remote-config` branch:

Remove the not updated firebase database and restart with a new one.

**Comment by pyby** [comment]
As discussed with @defagos , `feature/reset-remote-config` proposition is also needed.
Now built and deployed in beta build iOS 351 and tvOS 7.

**Comment by defagos** [comment]
Not sure the problem has been fixed. Play RTS installed on my iPhone still shows view counts, even after they have been disabled remotely.

I am starting to ask myself if there may be an issue in Firebase itself.
