### ISSUE TITLE
Empty remote configuration value has to return nil for number property

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#170]
### Issue type

Incorrect behavior

### Description of the problem

FireBase configuration can return an empty value for a key.
`ApplicationConfiguration` API can return a nullable value for `numberForKey:`.

A `nil` value is expected when remote Firebase value is empty. 

### Environment information

* Application version: Any (included latest iOS 3.1.7 and tvOS 1.0.1)
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

**Comment by pyby** [comment]
A fix has been made on `feature/fix-empty-remote-configuration`.

**Comment by defagos** [comment]
Merged back into `develop`, thanks.
