### ISSUE TITLE
M1 project compatibility

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#174]
We still use CocoaPods, [not running natively on M1 yet](https://github.com/CocoaPods/CocoaPods/issues/9907). It is [possible](https://stackoverflow.com/a/65334677/760435) to use the `arch` command to run the command on Rosetta.

Proposal:

- We are the only ones building the project on M1, so there is no hurry. We can wait until CocoaPods properly run on M1.
- If support is not ready at the time we switch our development Macs to M1, we can update the Makefile so that the `pod` command is forced to run on Rosetta.

**Comment by defagos** [comment]
The application runs fine on M1, except when playing on-demand audio. This is an `AVFoundation` issue, see our corresponding [SRG Media Player issue](https://github.com/SRGSSR/srgmediaplayer-apple/issues/101).

**Comment by defagos** [comment]
Still not working correctly on macOS 11.6 with our 3.3.0 version built using Xcode 13 and the iOS 15 SDK. Guess we should report this issue to Apple.

**Comment by defagos** [comment]
I confim that version 3.4.0 now crashes on M1, while 3.3.0 wasn't. The stack trace is not the same, but it is likely [related to our new CarPlay support](https://twitter.com/marcoarment/status/1439232332456763397). We should check what happens on Monterey.

**Comment by defagos** [comment]
The CarPlay-related crash is fixed when running the application on macOS Monterey.

**Comment by pyby** [comment]
@defagos Thank you for the tests on Monterey.
A Mac mini M1 with Big Sure has the same crash with production version 3.4.0.

So, I updated the "Make this app available" to "MacOS 12.0" for the 5 Play SRG application on AppStoreConnect.

For now, I didn't pass the "Verify compatibility" check, proposed by Apple.

**Comment by defagos** [comment]
Here are the steps to compile the project on M1:

1. Edit the `Application.xcconfig` files and remove `EXCLUDED_ARCHS`.
2. Remove the same `EXCLUDED_ARCHS` code from the Podfile.
3. Use Google Cast SDK binaries with arm64 simulator support.

Of course the first two changes must be made so that compilation on Intel Macs remains possible. Moreover Google is working on arm64 [simulator binaries](https://issuetracker.google.com/issues/1740488229, not sure if they will be available with CocoaPods as well, otherwise we'll need a way to download the `XCFramework`.

Alternatively, it might be possible to use a [hack](https://bogo.wtf/arm64-to-sim.html) on M1 to tweak the binary integrated with CocoaPods. If all solutions fail it might be possible to [tweak the project](https://stackoverflow.com/questions/58635911/exclude-pod-when-porting-to-mac-with-catalyst) so that binaries are not linked with the iOS simulator build on M1, but that requires conditional compilation and it is likely an ugly solution.

With changes 1 and 2 made at least the tvOS project compiles fine on M1, as it does not use the Google Cast SDK.

**Comment by pyby** [comment]
Google provided a beta version with dynamic XCFrameworks: https://issuetracker.google.com/issues/174048822

- We created a temporary SPM repository to distributed it: https://github.com/SRGSSR/GoogleCastSDK-ios-no-bluetooth
- Fix an issue in a `Info.plist` of `ios-arm64/GoogleCast.framework`: `DTSDKName`, `DTPlatformName` and `CFBundleSupportedPlatforms` MUST declare an "iphoneos" platform, not an "iphonesimulator" one.

Proposition is on `feature/googlecast-sdk-xcframework` branch.

**Comment by pyby** [comment]
The Play iOS 3.5.1-378 build is released in production and validated by Apple as well.

Both [Play iOS 3.5.1-378](https://github.com/SRGSSR/playsrg-apple/releases/tag/ios%2F3.5.1-378) and [Play tvOS 1.5.1-32](https://github.com/SRGSSR/playsrg-apple/releases/tag/tvos%2F1.5.1-32) builds were uploads on AppStoreConnect from a Mac mini M1 and Xcode 13.3.0
