### ISSUE TITLE
Update FetchImage or replace it

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#175]
### Issue type

Feature request

### Description of the problem

https://github.com/kean/FetchImage/releases

Play tvOS build uses FetchImage 0.3.0.
The 0.4.0 version has a breaking change.
We should decide next steps: Follow updates or create our own SwiftUI image view.

### Environment information

* Application version: tvOS 1.2.0
* iOS / tvOS version: Any
* Device: Any

**Comment by defagos** [comment]
Will be replaced with a custom implementation in version 3.2.0.

**Comment by defagos** [comment]
Implemented with `UIViewRepresentable`. State is much easier to manage (do not need to have a model which knows when an image must be reloaded or not).
