### ISSUE TITLE
Update Material tabs?

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#176]
Material tabs we were using (`MDCTabBar`) have been replaced with a new class (`MDCTabBarView`) [starting with version 119.0.0](https://github.com/material-components/material-components-ios/releases/tag/v119.0.0). 

I am not sure the new version supports all features we were using (most notably content centering), so an update requires some work. How images and texts are managed is also a questions for accessibility purposes.

For the moment I have fixed the version to 118.2.0.

**Comment by pyby** [comment]
The Material `MDCTabar` has been replaced by Pageboy: https://github.com/uias/Pageboy with https://github.com/SRGSSR/playsrg-apple/pull/486
