### ISSUE TITLE
Re-enable build parallelization

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#185]
Disabled to fix Xcode 13 compilation issue: https://openradar.appspot.com/radar?id=5029416321155072

Reenable for all schemes (set _Dependency Order_ instead of _Manual Order_ in all 10 application scheme build settings) and check this is fixed in later Xcode releases.

**Comment by defagos** [comment]
The problem has been fixed in Xcode 13.2 beta 2. I'll schedule this task for the next release (hopefully Xcode 13.2 will be available by then).

**Comment by pyby** [comment]
@defagos iOS 3.5.0 release builds and tvOS 1.5.0 release builds are successfully delivered to AppStoreConnect with Xcode 13.2 and build parallelisation enabled.

Next step for the project or the CI: [use the new mode](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes).
`defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1`

**Comment by defagos** [comment]
Great, thank you very much!
