### ISSUE TITLE
Cannot favorite or subscribe to shows anymore when no episodes are available on the show detail page

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#187]
With the replacement of the old show page with the new modern implementation (iOS 3.3.0 / tvOS 1.3.2) we have lost the possibility to favorite or subscribe to shows for which no episode is available.

This is due to the fact that the show header providing these feature buttons is not displayed when the collection is empty. This can probably be fixed for some screens by displaying an empty transparent cells instead of an empty list.

**Comment by pyby** [comment]
The `transparent` cell solution got our both agreements.
See `SectionViewModel`'s method `hasContent`.
