### ISSUE TITLE
Incorrect show favorite state on the player view

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#203]
If a show has been added to the favorites, the player favorite icon will disable itself after playing for a while.

### Issue type

Incorrect behavior

### Environment information

* Application version: 3.5.0
* iOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Play some media for a show belonging to the favorites.
1. Wait ~30 seconds.
1. The favorite icon toggles itself off without user intervention.

**Comment by defagos** [comment]
When refreshing because of a media metadata update, the show provided to the favorite status update method was `nil`. This regression was probably introduced when we implemented the timeshift experience.

The fix is available for review on `feature/favorite-status-bug`.

**Comment by pyby** [comment]
No a new issue in deed. Thanks @svenduvoisin .
