### ISSUE TITLE
Multi-selection gesture incorrectly triggers edit mode on non-editable screens

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#205]
Multi-selection gesture incorrectly triggers edit mode on non-editable screens (yeah, everything is in the title).

### Issue type

Incorrect behavior

### Environment information

* Application version: 3.5.0
* iOS / tvOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Open a non-editable detail view (e.g. Categories).
1. Drag with two fingers. Edit mode is incorrectly enabled and cells can be selected.

**Comment by defagos** [comment]
Fixed on `feature/selection-bug`.

**Comment by pyby** [comment]
Nice edge case found.

Thanks for the fix.
