### ISSUE TITLE
Push notification issues

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#206]
We identified two issues with push notifications:

- Incorrect sync between subscription status stored in user data and URNs registered with Airship.
- Push notifications not received on some devices at all.

**Comment by defagos** [comment]
We identified the issues:

- The incorrect sync was due to a code removed by mistake when performing some cleanup. This code was responsible of listening to user data preference changes and ensure that Airship tags are correctly in sync. It was restored.
- Some devices will not receive push notifications if they share the same [channel ID](https://support.airship.com/hc/en-us/articles/213492363-Device-Identifiers-for-iOS) as another device. Channel IDs are an Airship concept to deal with the fact that the device token used by APNS to identify the device might be updated. A device should be assigned a unique Channel ID mapping to a unique device token at any time. The Channel ID of an app installation is saved in user defaults, and since those are saved in iCloud backups it is possible that restoration on another device leads to the same Channel ID being used by more than one device. In this case only one device wins and has its device token 1:1 mapped to the Channel ID (which can be verified using Airship API). The other device is lost and does not receive any notification anymore. The only workaround to get a new Channel ID is to remove and install the app again.

**Comment by defagos** [comment]
I opened a dedicated [issue](https://github.com/urbanairship/ios-library/issues/313) for Airship. If users experience this issue the only workaround at the moment is to ask them to reinstall the app.

**Comment by pyby** [comment]
Sorry for our (my) responsibility of the removed code. We restore it, as @defagos said.

**Comment by defagos** [comment]
There is nothing we can do except wait for a possible Airship SDK update. We therefore agreed to close this issue.

**Comment by defagos** [comment]
I [confirm the issue has been fixed](https://github.com/urbanairship/ios-library/issues/313#issuecomment-1091138791). I tested the following three cases with:

- Play 3.5.0 using Airship 16.4.0 affected by the restoration issue.
- Play 3.6.0 using Airship 16.5.1 which contains the required fix.

### Case 1 ❌

1. Run Play 3.5.0 on device A.
2. Backup A to iCloud.
3. Erase device B and restore from iCloud backup of device A.
4. Run Play 3.5.0 on device B. Channel IDs are identical on both devices
5. Update to Play 3.6.0 on device B. Channel IDs are still identical.

### Case 2 ❌

1. Run Play 3.5.0 on device A.
2. Backup A to iCloud.
3. Erase device B and restore from iCloud backup of device A.
4. Run Play 3.6.0 on device B. Channel IDs are identical on both devices

### Case 3 ✅

1. Run Play 3.6.0 on device A.
2. Backup A to iCloud.
3. Erase device B and restore from iCloud backup of device A.
4. Run Play 3.6.0 on device B. A new channel ID is correctly generated for device B.

For the fix to be effective, the app must therefore be updated to a version running Airship 16.5.1+ on the device being backed up. This ensures the keychain attributes are correctly set in the backup. After restoration on another device Airship can then properly detect that a new channel ID must be generated.

This means in our case that the issue might still affect users, but that it will fade away with gradual adoptions of Play SRG versions running Airship 16.5.1+. Re-installing the application is still a viable (yet not always optimal) workaround in the meantime.
