### ISSUE TITLE
Truncated tab bar labels after device rotation

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#209]
Tab bar labels can be truncated after a rotation. I didn't see this in the past so this is likely a system change / regression introduced in a recent iOS 15.x release. The issue namely does not appear in the iOS 15.0 simulator.

![Screenshot 2022-05-17 at 14 00 44](https://user-images.githubusercontent.com/170201/168806287-0358adba-036e-4344-8ae0-c71f17fa79d0.jpg)

### Issue type

Incorrect behavior

### Environment information

* Application version: 3.6.0
* iOS: Seen with 15.4 / 15.5
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Play some content with Play RTS.
1. Rotate the player to landscape orientation,
1. Dismiss the player. "Recherche" is truncated.

**Comment by defagos** [comment]
This is related to the compact appearance, maybe because of the custom font we have. Just removing the compact bar appearance (which we never see anyway in our app) fixes the issue.

**Comment by defagos** [comment]
Fixed on `feature/tab-bar-label-truncation`.

**Comment by pyby** [comment]
Slide 27 of [WWDC19 Modernizing Your UI for iOS 13](https://devstreaming-cdn.apple.com/videos/wwdc/2019/224xnuourakjstfak/224/224_modernizing_your_ui_for_ios_13.pdf) session.

Strange new iOS 15.X bug. Nice and pragmatic fix @defagos. thanks
