### ISSUE TITLE
Update to Commanders Act version 5

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-apple#244]
**As a member of the analytics team** I want results to be gathered with the [new Commanders Act platform](https://github.com/CommandersAct/iOSV5/tree/master/TCServerSide#migration-v4-to-v5) requiring version 5 of the SDKs to be running in Play SRG.

# Acceptance criteria

- The Commanders Act SDK has been updated.

# Tasks

- [x] Update SRG Letterbox to version supporting Commanders Act version 5 (related to https://github.com/SRGSSR/srgletterbox-apple/issues/283).
- [x] Production / debug source keys have been properly set up.

**Comment by pyby** [comment]
Missing device language property reported. It was set by Commanders Act SDK 4 with `TC_LANGUAGE`. No more in Commanders Act SDK 5.

Discussed here:
https://github.com/SRGSSR/srganalytics-documentation/issues/8
https://github.com/CommandersAct/iOSV5/issues/9
