### ISSUE TITLE
iOS 17 / tvOS 17 compatibility

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#336]
### Issue type

As usual we must work on compatibility updates for iOS 17 and tvOS 17.

### Description of the problem

Build and check all features, UI and UX work as expected.

### List of tasks:

- [x] Update AppCenter to fix build: https://github.com/microsoft/appcenter-sdk-apple/issues/2484
- [x] Update AirShip to fix build: https://github.com/urbanairship/ios-library/issues/362
- [x] Fix iOS page layout issue when switching between apps. https://github.com/SRGSSR/playsrg-apple/pull/366
- [x] Fix tvOS Settings page layout issue with focused zoom button.
- [x] Fix tvOS Settings page layout issue when opening a modal.
- [x] Fix iOS error message when adding a program to a calendar.

**Comment by defagos** [comment]
It appears there is a layout issue with collections when building the Play app with the iOS 17 SDK, at least with beta 8:

1. Open a screen on an iPad (e.g. the home page).
2. Scroll down a bit so that the her section is cut in half.
3. Switch to another app (or send the app to the background).
4. Resume the app. The layout is broken.

**Comment by defagos** [comment]
The layout is due to incorrect horizontal layout traits propagation to the collection view layout, most likely due to [changes to the traits hierarchy](https://developer.apple.com/wwdc23/10057).

Maybe there is also a bug to report to Apple here.

**Comment by waliid** [comment]
> The layout is due to incorrect horizontal layout traits propagation to the collection view layout, most likely due to [changes to the traits hierarchy](https://developer.apple.com/wwdc23/10057).
> 
> Maybe there is also a bug to report to Apple here.

Indeed, prior to iOS 17, a child view controller inherited its trait collection from its parent view controller.
Starting from iOS 17, a child view controller inherits its trait collection from its superview.

**Comment by defagos** [comment]
The collection view issue has been reported as _iOS 17 regression: Collection view composition layout environment trait collection is incorrectly updated_, filed under FB13173057.

**Comment by pyby** [comment]
On tvOS 17, the `List` SwiftUI view used:
- "clipped to bounds": focused button layout is clipped leading and trailing.
- "wrong" secondary color on text for focused button when reappearing after presenting an other view controller above.

Here is a [video](https://github.com/SRGSSR/playsrg-apple/assets/380522/bbbdc3dc-d602-420a-af03-90ad9fee559d).

**Comment by defagos** [comment]
The focused button issue is a tvOS 17 regression, reported as _ tvOS 17 regression: Cell default focused appearance is broken after modal presentation dismissal_ under FB13183500.

**Comment by defagos** [comment]
The cell issue appearance FB13183500 has been fixed in tvOS 17.1 beta 1.
