### ISSUE TITLE
360° thoughts

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#66]
### Issue overview

> Check the correct option below

* [] Incorrect behavior
* [X] Feature request
* [ ] Crash
* [ ] Help / documentation
* [ ] Other: _classification_

### Description of the problem

From Sven feedbacks:

- On iPhone, we force the rotation to landscape for the full screen. Should we also force the camera rotation?

* Library version: 1.7.1
* iOS version: all
* Device: all

### Reproducibility

> Check the correct option below

* [X] Always reproducible
* [ ] Difficult to reproduce

### Code sample

> The easiest way to understand your issue is with a simple code sample. If you can provide one, please add a link to it here

[Code sample](https://github.com/username/repository)

### Steps to reproduce

> Provide step-by-step instructions about how to reliably reproduce the issue (or if not possible, with a good probability)

1. _Step 1_
1. _Step 2_
1. _Step 3_

**Comment by defagos** [comment]
I guess that 360° playback is not a priority anymore. I therefore think we can close this issue.
