### ISSUE TITLE
Add custom remote configuration of topic sections

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#74]
### Issue overview

* [] Incorrect behavior
* [X] Feature request
* [ ] Crash
* [ ] Help / documentation
* [ ] Other: _classification_

### Description of the problem

The topic sections list is define for all topic in one remote configuration `topicSections`, or the new `topicSectionsWithSubtopics`.

The RTS topic PrimeTime hasn't most clicked request implemented. We can ask RTS if the they want it, but it looks like it's not relevant.

Option 1: `topicSections`to `latest` for all RTS Topic (like it's on the web portal).
Option 2: add the `topicSections` in the `topicHeaders` configuration to have a custom configuration for a topic, if needed.

### Environment information
* Application version: 2.7.10
* iOS version: Any
* Device: Any

### Reproducibility

* [X] Always reproducible
* [ ] Difficult to reproduce

**Comment by defagos** [comment]
Not relevant anymore with the introduction of PAC.
