### ISSUE TITLE
Description text shorten

### ISSUE THREAD

**Issue by svenduvoisin** [SRGSSR/playsrg-apple#81]
### The description text of a program does not show completely

* Library version: Nightly 331
* iOS version: any
* Device: tested on iPhone X, iPad 2018, iPhone 7Plus, iPhone 5C

### Reproducibility

Always reproducible

### Steps to reproduce

1. Choose "Émissions A à Z"
2. Select "T"
3. Choose "Temps Présent"
4. Choose any show
The description text beneath the show is shorten and ends with "..."

5. If device rotated to landscape mode, the description text is not visible anymore
6. When the device is rotated back to portrait mode, the text shows completely for a while, then is shorten

**Comment by defagos** [comment]
Guess this might be fixed as part of SwiftUI adoption.

**Comment by defagos** [comment]
The show page was rewritten and this issue cannot be reproduced anymore.
