### ISSUE TITLE
Some crashes on iOS 9

### ISSUE THREAD

**Issue by pyby** [SRGSSR/playsrg-apple#99]
### Issue type

Crash

### Description of the problem

I was looking Hockey app daily report.
[Statistics for 2018-11-16: 169 crashes for Play SRF](https://rink.hockeyapp.net/manage/app_stats?date=2018-11-16)

### Environment information

* Application version: 2.8.7
* iOS version: iOS 9.0.2 (up to 9.3.5)
* Device: all

### Reproducibility

Difficult to reproduce

**Comment by defagos** [comment]
iOS 9 support has been dropped. This issue can be closed.
